server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.89.1.30:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: logstream
    pipeline_stages:
      - regex:
          expression: '.*ModSecurity.*(?P<action>Access denied|Warning).*\[id "(?P<rule_id>\d+)"\].*client: (?P<client_ip>[\d.]+)'
      - labels:
          action:
          rule_id:
          client_ip:
